@echo off
CD /d %~dp0

devmanview.exe /disable "PCI Data Acquisition and Signal Processing Controller"
devmanview.exe /disable "PCI Encryption/Decryption Controller"
devmanview.exe /disable "PCI Simple Communications Controller"
devmanview.exe /disable "PCI Memory Controller"
devmanview.exe /disable "PCI standard RAM Controller"
devmanview.exe /disable "AURA LED Controller"
devmanview.exe /disable "Communications Port (COM1)"
devmanview.exe /disable "Intel SMBus"
devmanview.exe /disable "Intel Management Engine"
devmanview.exe /disable "NVIDIA Virtual Audio Device (Wave Extensible) (WDM)"
devmanview.exe /disable "NvModuleTracker Device"
devmanview.exe /disable "NVVHCI Enumerator"
devmanview.exe /disable "AMD PSP"
devmanview.exe /disable "AMD SMBus"
devmanview.exe /disable "AMD Crash Defender Service"
devmanview.exe /disable "AMD External Events Utility"
devmanview.exe /disable "UMBus root bus enumerator"
devmanview.exe /disable "Micosoft GS Wavetable Synth"
devmanview.exe /disable "Microsoft Hyper-V Virtualization Infrastructure Driver"
devmanview.exe /disable "Virtual Disk Enumerator (Microsoft)"
devmanview.exe /disable "Enumerator of virtual network adapters NIC"
devmanview.exe /disable "Composite Bus Enumerator"
devmanview.exe /disable "Remote Desktop Device Redirector Bus"
devmanview.exe /disable "Base System Device"
devmanview.exe /disable "Legacy device"
devmanview.exe /disable "Microsoft Kernel Debug Network Adapter"
devmanview.exe /disable "Performance Monitor"
devmanview.exe /disable "SM Bus Controller"
devmanview.exe /disable "System Speaker"
devmanview.exe /disable "Microsoft Radio Device Enumeration Bus"
devmanview.exe /disable "Direct memory access controller"
devmanview.exe /disable "Programmable Interrupt Controller"
